"""
DeployGuard AI - GitHub PR Automated Comment Generator
Generates clean, GitHub-flavored Markdown comments for PR risk assessment.
"""
from typing import Any


def generate_pr_comment(risk_ledger: dict[str, Any], blast_radius: dict[str, Any]) -> str:
    score = risk_ledger.get("overall_score", 0)
    level = risk_ledger.get("level", "low").upper()
    recommendations = risk_ledger.get("recommendations", [])
    dimensions = risk_ledger.get("dimensions", [])
    nodes = blast_radius.get("nodes", [])

    badge_emoji = "🟢" if score < 40 else "🟡" if score < 70 else "🔴"

    lines = [
        f"## {badge_emoji} DeployGuard AI — Risk Assessment ({level} RISK: {score}/100)",
        "",
        "> **Operational Decision Support**: Every risk dimension below is traceable to evidence.",
        "",
        "### 📊 Risk Dimensions",
        "",
        "| Dimension | Score | Weight | Reason |",
        "|---|---|---|---|",
    ]

    for dim in dimensions:
        lines.append(f"| **{dim.get('label')}** | `{dim.get('score')}/100` | `{int(dim.get('weight', 0) * 100)}%` | {dim.get('reason')} |")

    lines.extend([
        "",
        f"### 🌐 Blast Radius ({len(nodes)} Services Impacted)",
        "",
    ])

    for node in nodes:
        health_icon = "🔴" if node.get("health") == "critical" else "🟡" if node.get("health") == "degraded" else "🟢"
        lines.append(f"- {health_icon} **{node.get('label')}** (`{node.get('tier')}`) — Impact Score: `{node.get('impact_score')}/100`")

    if recommendations:
        lines.extend([
            "",
            "### 💡 Recommended Verification Steps",
            "",
        ])
        for rec in recommendations:
            lines.append(f"- [ ] {rec}")

    lines.extend([
        "",
        "---",
        "_Generated by [DeployGuard AI](https://github.com/kingggg5/pos) · Evidence-Backed Operational Ledger_",
    ])

    return "\n".join(lines)
