"""initial workspace platform

Revision ID: 0001
Revises: 
Create Date: 2026-07-28 22:25:19.515051
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active_change_id', sa.String(length=80), nullable=True),
    sa.Column('active_incident_id', sa.String(length=80), nullable=True),
    sa.Column('service_graph', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('auth_provider', sa.String(length=40), nullable=False),
    sa.Column('provider_subject', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_subject')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('access_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('changes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('repository', sa.String(length=240), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployment_status', sa.String(length=40), nullable=False),
    sa.Column('deployment_environment', sa.String(length=80), nullable=False),
    sa.Column('changed_services', sa.JSON(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('test_coverage', sa.Float(), nullable=False),
    sa.Column('rollback_ready', sa.Boolean(), nullable=False),
    sa.Column('observability_score', sa.Float(), nullable=False),
    sa.Column('previous_failures', sa.Integer(), nullable=False),
    sa.Column('risk', sa.JSON(), nullable=False),
    sa.Column('blast_radius', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changes_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=160), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_audit_workspace_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('correlated_change_id', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('hypotheses', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['correlated_change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_correlated_change_id'), ['correlated_change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_repository_id', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=240), nullable=False),
    sa.Column('default_branch', sa.String(length=160), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('connection_state', sa.String(length=24), nullable=False),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'provider_repository_id', name='uq_workspace_provider_repository')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.create_index('ix_pending_invitation_workspace_email', ['workspace_id', 'email', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_memberships_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('incident_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=80), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_feedback_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_feedback_incident_id'))

    op.drop_table('incident_feedback')
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_user_id'))

    op.drop_table('workspace_memberships')
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_email'))
        batch_op.drop_index('ix_pending_invitation_workspace_email')

    op.drop_table('workspace_invitations')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_workspace_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_correlated_change_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_workspace_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))

    op.drop_table('workspaces')
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changes_scenario_id'))

    op.drop_table('changes')
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_expires_at'))

    op.drop_table('access_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_is_active'))

    op.drop_table('scenarios')
    # ### end Alembic commands ###
